# Site configuration for Yeoman Jekyll project

## Process RWRW app.name
name: RWRW add var
## Process RWRW jk
description: RWRW blank
# If Yo is setting up do we need this?
# url: 'http://localhost:9000'

## Process RWRW jk
# author :
#   name       : RWRW populate
#   email      : RWRW populate
#   github     : RWRW populate username
#   twitter    : RWRW populate username

## Custom paths
source:      .
destination: ./_site
plugins:     ./_plugins

## Grunt handles compiling and reloading Jekyll.
server: false
auto: false

# Exclude files from compilation. Excludes .dot and _underscore files and
# directories by default.
exclude: ['bower.json', 'Gruntfile.js', 'package.json', 'config.rb', 'readme.md', 'travis.yml']

# Specifically include files that would have otherwise been excluded.
include: ['.htaccess']

# Default post path style
## Process RWRW jk
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: RWRW var

## RWRW Maruku by default, so if maruku chosen do not render
# Might need further conig (smartypants)
## Process RWRW jk
markdown: RWRW var
# rdiscount
# kramdown
# redcarpet
# maruku

### RWRW These are the defaults
# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex
# rdiscount:
#   extensions: []
# redcarpet:
#   extensions: [ fenced_code_blocks, smart ]
# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

## Process RWRW jk
# Highlight tag with the Pygments library.
pygments: RWRW Var bool (def false or true)
# Publish posts with future date.
future: RWRW [boolean]
# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: RWRW [per_page]
