# Base Jekyll configuration

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile. There is also a
# _config.build.yml to set custom overrides for `grunt build`.

name: <%= appname %>
description: <%= jekDescript %>

author:
  name: <%= author %>
  email: <%= email %>
  github: <%= github %>
  twitter: <%= twitter %>

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: [<% if (cssPre) { %>'<%= cssPreDir %>', <% } %><% if (jsPre) { %>'<%= jsPreDir %>', <% } %>'<%= imgDir %>', '<%= cssDir %>', '<%= jsDir %>', '<%= fontsDir %>', 'bower_components', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: <%= jekPost %>

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true<% if (jekPage) { %>

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: <%= jekPage %>
paginate_path: 'page:num'<% } %>

# Markdown library
markdown: <%= jekMkd %>
# Markdown library options<% if (jekMkd === 'maruku') { %>
# maruku:
  # use_tex:    false
  # use_divs:   false
  # png_engine: blahtex
  # png_dir:    images/latex
  # png_url:    /images/latex<% } %><% if (jekMkd === 'rdiscount') {%>
# rdiscount:
  # extensions: []<% } %><% if (jekMkd === 'kramdown') {%>
# kramdown:
  # auto_ids: true
  # footnote_nr: 1
  # entity_output: as_char
  # toc_levels: 1..6
  # use_coderay: false
  # coderay:
  #   coderay_wrap: div
  #   coderay_line_numbers: inline
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: style<% } %><% if (jekMkd === 'redcarpet') {%>
# redcarpet:
  # extensions: [ fenced_code_blocks, smart ]<% } %>

# Use Pygments to highlight code blocks
pygments: <%= jekPyg %>
